### ISSUE TITLE
Make routing great again!

### ISSUE THREAD

**Issue by rehandalal** [mozilla/normandy#1065]
Our current front-end routing in react/redux ain't so great. It would be really nice:
- [ ]  to have a cleaner way of handling the trailing slash at the end of URLs
- [x]  to have named routes

**Comment by andymikulski** [comment]
The basis for named routes landed in #1076

**Comment by andymikulski** [comment]
I've played a little bit with figuring out a cleaner approach to the routes and landed on something that looks like this:

```
import { Route, lilRouterize, replaceUrlVariables } from './routerUtils';

const routes = lilRouterize({
  '/': new Route('home', Gateway),

  '/recipe/': new Route('recipe-listing', RecipeListing),
  '/recipe/new/': new Route('create-recipe', CreateRecipePage),
  '/recipe/:recipeId/': new Route('view-recipe', RecipeDetailPage),
  '/recipe/:recipeId/edit/': new Route('edit-recipe', EditRecipePage),
  '/recipe/:recipeId/clone/': new Route('clone-recipe', CloneRecipePage),
  '/recipe/:recipeId/approval_history/': new Route('approval-history', CloneRecipePage),
  '/recipe/:recipeId/rev/:revisionId/': new Route('view-revision', RecipeDetailPage),
  '/recipe/:recipeId/rev/:revisionId/clone/': new Route('clone-revision', CloneRecipePage),

  '/extension/': new Route('extension-listing', ExtensionListing),
  '/extension/new/': new Route('new-extension', CreateExtensionPage),
  '/extension/:extensionId/': new Route('view-extension', EditExtensionPage),
});
```

The `lilRouterize` function converts this human-readable list into the format lil-router expects. I like this approach since it's a bit easier to reason about, but I'm open to feedback.

**Comment by mythmon** [comment]
That looks good to me. The idea of having a flat structure that gets unpacked into the tree is something we've talked about positively before. It definitely seems like a good way to go.

I've been pondering if the `Route` class should also take in the url definition (`/recipe/:recipeId/edit/`), and just get a list of Route objects, instead of a map. I'm not sure if that would help or hurt anything though.

Also, how do crumb title and `parentSlug`s fit into this? Would it be better for `Route` to take an options object instead, like this?

```js
new Route({
  url: '/recipe/:recipeId/clone/',
  crumb: 'Clone',
  slug: 'recipe-clone',
  parentSlug: 'recipe-detail',
})
```

Also, some useful inspiration that I've been thinking about is [the way Django does routing](https://docs.djangoproject.com/en/dev/topics/http/urls/#examples). We definitely don't need to do things the way they did, but they can prove as a source of useful ideas if we get stuck.
