### ISSUE TITLE
Ability to stage and test changes to recipes

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#1073]
It would be helpful for testing risky changes to existing recipes if we could submit and approve changes to recipes and make them available for testing, but without actually publishing the changes. Currently, changes to existing recipes can only be tested by creating separate recipes to test the changes with.  

Perhaps by having a separate API endpoint for staged changes?

**Comment by mythmon** [comment]
I think the future of this lies in the [normandy-devtools](https://github.com/mozilla/normandy-devtools) being able to execute any revision of a recipe. That doesn't require any additional server side changes.

**Comment by shell1** [comment]
This is for QA test-ability of pre-release, non-published recipes.  Putting on server is not where we want to address this (adds publishing complexity).  Revisions in general needs to simplified.

The limitation was that devtools could only run current version of the recipe and only pulls recipes from production - not stage.  So this means they cannot test pre-released recipes.

BUT rehan now has a local patch for normandy devtools (in that repo) working so that QA can pull from different environments or run arbitrary recipes (grab JSON from a revisions and dump into the tool).  that way we couple put "unapproved" recipe up - that can be tested.  He will submit it as pull request to normandy dev tools repo that will land in devtools.  and then they can install from github itself.  

sidenote: signature issue follow up with tyler to verify what he is seeing there.  rehan installed fine.
