### ISSUE TITLE
Button to dump recipe branch names to string array?

### ISSUE THREAD

**Issue by jtg567** [mozilla/normandy#1074]
I'm writing a quick spark script to count clientIds overall and by branch for a pref-flip study and realized it would be a little faster if there was a button in the UI to dump these 9 branch names to an array in a textbox or directly to the clipboard.

e.g. `["branch1", "branch2", ..., "branchN"]`

**Comment by mythmon** [comment]
Today there is a button that shows up on hover that copies the string value of just about any field in the arguments. Right now if you click on that for the branches, you get this text on your clipboard:

```
List [ Map { "ratio": 1, "slug": "control", "value": false }, Map { "ratio": 1, "slug": "variant", "value": true } ]
```

I think it would be easy and very sane to make this return normal JSON instead of Immutable.js stringifications, which would result in this:

```json
[{"ratio": 1, "slug": "control", "value": false}, {"ratio": 1, "slug": "variant", "value": true}]
```

@jtg567 Would that work for your use case?

**Comment by andymikulski** [comment]
Crazy thought: do we want to give the option to copy CSV as well?
