### ISSUE TITLE
Recipe server response returns empty population criteria fields (countries, channel, locale)

### ISSUE THREAD

**Issue by acmiyaguchi** [mozilla/normandy#1125]
https://github.com/mozilla/normandy/blob/1553a2ebac90a7004975874401a8fb2c6e10303e/recipe-server/normandy/recipes/models.py#L331-L340

The [`api/v1/recipe` response](https://normandy.services.mozilla.com/api/v1/recipe/) returns the list of recipes. Most of the responses contain a valid filter and extra filter expression, but are missing the raw fields for creating these filters. `countries`, `channel`, and `locale` are all empty lists.

I would expect these fields to be populated.

**Comment by mythmon** [comment]
The `country`, `channel`, and `locale` fields aren't exposed in the UI, and so are never used. They are empty in the API because there is no data. The semantics here are that `extra_filter_expression`, `countries`, `channels`, and `locales` are used to create `filter_expression`. In practice, only `extra_filter_expression` has any data.
