### ISSUE TITLE
Change to recipe payload schema to simplify client side verification

### ISSUE THREAD

**Issue by mostlygeek** [mozilla/normandy#1211]
This is a follow up to #1210. The [current JSON (big)](https://normandy.cdn.mozilla.net/api/v1/recipe/?enabled=1&format=json) response from the server looks like this: 

```js
[
  {
    "recipe": { ... },  // this is the signed portion
    "signature": { ... }, // the signature for the recipe
  },
  { ... } // the recipe-signature pairs are repeated for each recipe
]
```

The problem with this schema is that we force the client to recreate the original JSON byte for byte.  If one bit is off the signature validation will fail.  This means maintaining a new type of JSON library and serialization standard across client and server JSON implementations. 

This would be a better schema: 

```js
[
  {
    "recipe_json": "{ ... }",  // recipe is just a string
    "signature": { ... }, // the signature for the recipe
  },
  { ... } // the recipe-signature pairs are repeated for each recipe
]
```

Simply send the original JSON. The client can verify it without any additional complexity.  When it has been verified it can deserialize it into a proper javascript object.

**Comment by mythmon** [comment]
One concern is that we will have to continue supporting old versions of the client. In order to make this change we'll either have to

1. Include both `recipe` (serialized) and `recipe_json` (stringified), which would roughly double the payload size.
2. Add a new endpoint, such as `/api/v1/recipe/signed-json/`
3. Change the API version.
    * The v2 API doesn't have a signed endpoint yet, we could implement v2's signed endpoint in this way.

It will also make the API less human readable, and harder to work with using tools like curl. That's probably a minor issue though.

**Comment by mostlygeek** [comment]
I prefer the V2 approach.

**Comment by mostlygeek** [comment]
Notes from the wednesday standup: 

With kinto the signature algorithm is: `sign(<JSON of all records in a collection>)`. Since kinto can synchronize only the changes, they need to reconstruct `<JSON of all records in a collection>` on the client side to verify the signature.

**Comment by mostlygeek** [comment]
Closing this proposal since we are not likely to do anything with this for a while.
