### ISSUE TITLE
Study Name is listed as "Name" (twice)

### ISSUE THREAD

**Issue by peterbe** [mozilla/normandy#1213]
<img width="840" alt="screen shot 2018-03-28 at 1 07 32 pm" src="https://user-images.githubusercontent.com/26739/38053480-11b2367e-3289-11e8-9132-da449eb7452b.png">

**Comment by mythmon** [comment]
This is because of the [schema for the opt-out-study name](https://github.com/mozilla/normandy/blob/master/recipe-server/client/actions/opt-out-study/package.json#L8-L40) has a key called `name`. The UI here is generated automatically from the data.

The improvement that could be made here is to make the first "name" more closely associated with the Action header, since that is why it is there.
