### ISSUE TITLE
Allow Addons to be updated in Addon Studies

### ISSUE THREAD

**Issue by mostlygeek** [mozilla/normandy#1419]
In a postmortem with the shield team it was requested that addons should be updatable in addon-studies.  The ask is so we can fix bugs in addons.  However, I was under the impression that this was originally a feature, that addons can't be updated. 

@mythmon could you share what the rational was for addons not being updated as well as what it would involve to make it so they can be updated.

**Comment by mythmon** [comment]
I'm not confident why it was done this way originally, but I have three theories:

1. A study is "supposed to be" immutable once it launches, and there is a concern that modifying recipes mid-study could complicate or even invalidate a study. In practice this isn't a helpful thing to enforce though.
2. Add-on studies were developed on a compressed timeline, and many things were cut to hit our schedule. The ability to update in place could have been cut at this time as non-critical.

Either way, it is definitely something we should implement, as not having it causes far more problems than having it likely would have caused.

All that being said, this is not the right place for this issue, since this repo is only dealing with the API server now. Since the API server allows changing the XPI of an add-on study, there is no problem related to the code in this repo. I've filed [bug 1474413](https://bugzilla.mozilla.org/show_bug.cgi?id=1474413) instead.
