### ISSUE TITLE
Filter object's locales, countries and channels is not validated

### ISSUE THREAD

**Issue by peterbe** [mozilla/normandy#1544]
I just managed to save a recipe's filter object, using my [unfinished branch](https://github.com/mozilla/delivery-console/issues/176), that set the filter object to something that is definitely not in the `Country` model. 

E.g.
```
In [7]: r.refresh_from_db()

In [8]: r.filter_object
Out[8]:
[{'type': 'locale', 'locales': ['sv-SE']},
 {'type': 'country', 'countries': ['SE', 'junkjunkjunk']}]

```

**Comment by peterbe** [comment]
@mythmon I have no qualms adding a little code to the api serializer validation code. **but...** if the UI is good to only allow you to select from the available options in drop-down, the only way you'd be able to do something like this is if you use `curl`, if you catch my drift. Even then, is it that horrible? What if you really really mean "Country of Doesnotexististan"?

I appreciate that we have the extra_filter_expression for this stuff plus you have reviewers who will look over the filter objects too. 

Any last thoughts before I start coding something?

**Comment by peterbe** [comment]
@rehandalal too ^ ?

**Comment by mythmon** [comment]
I think the API should guarantee that the countries (and other data) used in filter objects are correct. Normandy should not rely on any client validation to maintain correctness of the data, since curl and other clients besides DC can exist. Just because we are developing both ends doesn't mean we should stop distrusting the user.
