### ISSUE TITLE
Heartbeat should catch and properly report inability to connect to Autograph

### ISSUE THREAD

**Issue by mythmon** [mozilla/normandy#1607]
https://sentry.prod.mozaws.net/operations/normandy-stage/issues/4903226/

```
gaierror: [Errno -2] Name or service not known
  File "urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):

NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f1d775b20b8>: Failed to establish a new connection: [Errno -2] Name or service not known
  File "urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)

MaxRetryError: HTTPSConnectionPool(host='content-signature.stage.mozaws.net', port=443): Max retries exceeded with url: /chains/normandy.content-signature.mozilla.org-20191015.stage.chain (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1d775b20b8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
  File "requests/adapters.py", line 449, in send
    timeout=timeout
  File "urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))

ConnectionError: HTTPSConnectionPool(host='content-signature.stage.mozaws.net', port=443): Max retries exceeded with url: /chains/normandy.content-signature.mozilla.org-20191015.stage.chain (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1d775b20b8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
(8 additional frame(s) were not displayed)
...
  File "dockerflow/django/middleware.py", line 45, in process_request
    return view(request)
  File "dockerflow/django/views.py", line 57, in heartbeat
    detail = heartbeat_check_detail(check)
  File "dockerflow/django/views.py", line 79, in heartbeat_check_detail
    errors = check(app_configs=None)

ConnectionError: HTTPSConnectionPool(host='content-signature.stage.mozaws.net', port=443): Max retries exceeded with url: /chains/normandy.content-signature.mozilla.org-20191015.stage.chain (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1d775b20b8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```

**Comment by sciurus** [comment]
It's okay if you want to stop sending connection errors to autograph or other backing services to sentry, but if you do please add counters that tracks the error frequencies in datadog. Otherwise after the fact we'll have no way of telling what caused a particular heartbeat to fail.

**Comment by mythmon** [comment]
The plan here is to report errors connecting to backing services in the output of heartbeat instead of throwing errors that go to sentry. Specifically we won't be doing any retry. The details for what's causing heartbeat to fail are included in the output of the request. Does that work?

**Comment by sciurus** [comment]
I agree we should handle things such that the failures are actually reported in heartbeat output instead of just triggering a Sentry error. But if we just report connectivity errors there, we'll loose some insight for a couple reasons:

1) PIngdom doesn't page us until there are consecutive failed requests over a few minutes. This means there could be intermittent connectivity issues that don't page. Right now we would notice them via Sentry.
2) Pingdom doesn't record the response body. So if I'm paged for a  failing heartbeat, but the alert clears before I can test it myself, I can't see what specifically was failing. Right now if it was a connectivity issue, I could see it via Sentry.

For some things (e.g. the db) this is not as big a concern, since pages outside of heartbeat will be accessed and throw sentry errors. But for other things (e.g. autograph) that are little-used it would be an issue.

So I think we still need some way to track connectivity problems historically. Some ideas are to either capture the error but still send it to sentry, log it, or send counters for the errors to datadog.

**Comment by mythmon** [comment]
I think that this is probably a bigger issue. We've tried pretty hard to make sure that heartbeat doesn't ever throw errors and instead reports what it finds with the appropriate error code. The fact that the response we are sending gets thrown away in the common case is pretty surprising.

I think either logging the errors or sending them to sentry (or both) along with returning a response with the details is a good idea. However, I think that's a problem for a different issue.

**Comment by peterbe** [comment]
The problem with reporting operational stuff with Sentry is that it causes noise. It's dangerous because we should always take all/any Sentry errors seriously and almost always the outcome should be a filed GitHub issue followed by a code patch. 

If we (ab)use Sentry for operational logging, we risk the developers (i.e. mike, rehan, myself) to "learn to ignore" Sentry because there's nothing we can do. 

The fact that Pingdom just says "It was bad" is a problem which bothers me. Can we just ditch Pingdom and instead switch to something that can contain the body of the heartbeat HTTP output?

Sounds like we need a/some logging solution. What about the regular Python logging? What if we did something like this:

```python
def heartbeat():
    ...
    try:
       check_autograph_connection()
    except autograph_operational_exceptions, err:
       msg = f"{err.__class__.__name__} error: {err} "
       logger.warn(msg)
       errors['autograph'] = msg
    ...
```

Then, in theory, the OPs team would 1) Get an SMS about operational badness and 2) Check the logs to see what the error *was*. 

(Disclaimer; I don't know/remember how normandy currently does these heartbeat checks in detail)

Perhaps, this is the time to step up and connect Normandy and Datadog. We can use the same stack as Tecken (`markus[datadog]`) and ditch the idea of Python logging. Or, do both like Tecken does. We can do something like:

```python
def heartbeat():
    ...
    try:
       check_autograph_connection()
    except autograph_operational_exceptions, err:
       msg = f"{err.__class__.__name__} error: {err} "       
       logger.warn(msg)
       errors['autograph'] = msg
       metrics.incr('heartbeat_failure', tags=['service:autograph'])
    ...
```

**Comment by peterbe** [comment]
Sentry issue: [NORMANDY-STAGE-28](https://sentry.prod.mozaws.net/operations/normandy-stage/issues/4951178/)
