### ISSUE TITLE
Remove preference-experiment from this repo

### ISSUE THREAD

**Issue by glasserc** [mozilla/normandy#1650]
Once https://bugzilla.mozilla.org/show_bug.cgi?id=1440779 lands, we can remove it from this repo.

This represents follow up work that is part of https://bugzilla.mozilla.org/show_bug.cgi?id=1436129.

**Comment by mythmon** [comment]
Unfortunately, we can't do this so soon. Although that bug landing will make *that* version of Firefox no longer need the server-hosted action code, there will still be others that need it.

If we only wanted to support the release version of Firefox, we'd have to wait 12 weeks until firefox 66 becomes release. However, we also want to continue to support Firefox ESR 60, which will still be supported until October of 2019. Even then we may want to keep support for older versions for a longer time.

We're going to be stuck with this code for quite some time. It might make sense to talk about moving it to another repository, or organizing the code differently. I'd be very happy to get rid of the JS parts of the repository. I don't think this issue is right though.

**Comment by peterbe** [comment]
> It might make sense to talk about moving it to another repository, or organizing the code differently.

Would it be an option to just copy the (compiled) JS and dump it on a disk somewhere. E.g. inside this repo. Kinda like when we checked in `static/js/jquery.min.js` in the olden days. If that worked we could drop a lot of JS related infra stuff from this repo. 

Perhaps it's not worth it since we don't suffer that much from the status quo at the moment now that we've got the CircleCI karma stuff all figured out.

**Comment by mythmon** [comment]
We've stopped doing that sort of thing because of the problems we ran into "in the olden days". It would make it unclear without a lot of diligence what versions of libraries, if any, were used in the compiled source, and it makes it unclear how to update the code if needed in the future. Whatever we do, I think we should keep all the build tools and NPM packaging intact.

However, we may be able to reduce or remove some of our dependence on build tools and libraries. We probably don't need to babelify and compile our code as much any more. Maybe we should work on slimming things down.
