### ISSUE TITLE
Do we still need a custom pip and pipstrap?

### ISSUE THREAD

**Issue by peterbe** [mozilla/normandy#1733]
I can't (grep) find any use of https://github.com/mozilla/normandy/blob/master/bin/pipstrap.py 
Can we delete that now?

Also, why do we specify a [custom `pip` here](https://github.com/mozilla/normandy/blob/f060dd6d5b15a9c396da1fe99a8fb662f9d3afe2/Dockerfile#L21)?

Our [`3.7-slim`](https://github.com/docker-library/python/blob/344fd4f05b1e81dd97f8334e30035c0359dfde7f/3.7/stretch/slim/Dockerfile#L104) already comes with a pip. 

Note, as of right now, the pip you get in `3.7-slim` is **19.0.1** but the latest version on Pypi is [19.0.2](https://pypi.org/project/pip/19.0.2/) which came out a couple of days ago. So with pyup on our side, we can get a couple of days fresher `pip` when maintained explicitly.

**Comment by mythmon** [comment]
A bit of history: we started using pip hashes before most of the standard images had a version of pip that supported hashes. Because of that we had to get our own version of pip that we could guarantee was safe. That was what pipstrap was for.

Nowadays, as you point, we have modern pips in our CI issues. We can safely remove all this weirdness and just use the pip provided by the environment (as long as we still require hashes).
