### ISSUE TITLE
Service info endpoint is broken

### ISSUE THREAD

**Issue by mythmon** [mozilla/normandy#1747]
Visiting `/api/v3/service_info/` on prod  produces an error about not having a reverse match for the logout route. This endpoint is useful for delivery console.

https://sentry.prod.mozaws.net/operations/normandy-prod/issues/5235770/

```
NoReverseMatch: Reverse for 'logout' not found. 'logout' is not a valid view function or pattern name.
(8 additional frame(s) were not displayed)
...
  File "rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "rest_framework/reverse.py", line 50, in reverse
    url = _reverse(viewname, args, kwargs, request, format, **extra)
  File "rest_framework/reverse.py", line 63, in _reverse
    url = django_reverse(viewname, args=args, kwargs=kwargs, **extra)

NoReverseMatch: Reverse for 'logout' not found. 'logout' is not a valid view function or pattern name.
```

**Comment by peterbe** [comment]
Note-to-self...

Current Prod:
```
▶ curl https://normandy.cdn.mozilla.net/api/v3/service_info/
<h1>Server Error (500)</h1>
```
Current `master`:

```
▶ curl http://localhost:8000/api/v3/service_info/
{"github_url":"https://github.com/mozilla/normandy","logout_url":"/logout/","peer_approval_enforced":true,"user":null}
```

Note that https://sentry.prod.mozaws.net/operations/normandy-prod/issues/5235770/ talks about `/api/v2/service_info/` not `/api/v3/service_info/` but I don't think it matters.

**Comment by peterbe** [comment]
And current Dev too:

```
▶ curl https://dev.normandy.nonprod.cloudops.mozgcp.net/api/v3/service_info/
<h1>Server Error (500)</h1>
```

**Comment by peterbe** [comment]
So many questions. 
The error happens because `settings.ADMIN_ENABLED` is False so [this URL pattern](https://github.com/mozilla/normandy/blob/7efe226ba52c3689137ae28350a9cb508009ad51/normandy/control/urls.py#L16-L21) is never registered. 
You could also say it happens because `settings.OIDC_LOGOUT_URL` isn't set. So many questions...

1. Is this `settings.OIDC_LOGOUT_URL` a relic from the disbanded past when we used Nginx lua to do authentication? Can we ditch it?
2. What is this `normandy.control` app? The only thing I can see of it is to have a HTML page if you go to the root of the Normandy API domain's root URL. 
3. Can we ditch the URL patterns for `login/` and `logout/` now that we no longer use/need the Django Admin?

**Comment by mythmon** [comment]
>     1. Is this `settings.OIDC_LOGOUT_URL` a relic from the disbanded past when we used Nginx lua to do authentication? Can we ditch it?

Yes, and yes.

>     2. What is this `normandy.control` app? The only thing I can see of it is to have a HTML page if you go to the root of the Normandy API domain's root URL.

`normandy.control` is the app that served up Delivery Console's predecessor, which we called "the control interface". It used to be served at the root of the domain, so now we have that HTML page at the root that directs people to Delivery Console. We can probably remove it soon.

>     3. Can we ditch the URL patterns for `login/` and `logout/` now that we no longer use/need the Django Admin?

We can remove those URLs from this view. Lets save actually removing the URL patterns for a more concerted effort to disable the admin everywhere.
