### ISSUE TITLE
Extensions should not allow files to be overwritten

### ISSUE THREAD

**Issue by rehandalal** [mozilla/normandy#1797]
Currently if a user uploads a new extension with a filename that matches an existing one, we just overwrite the old file. This is pretty dangerous and we should not allow it.

Additionally we may want to rename files to match the standard naming convention:
`{addon-id}-{version}-signed.xpi`.

**Comment by mythmon** [comment]
> Additionally we may want to rename files to match the standard naming convention

I'm not so sure this is a good idea. I recently found a problem purely by knowing the exact original file name (it was `-signed-testing` instead of `-signed`). We already expose all the details contained in the standard name in the API, and we're moving towards building XPIs more automatically in other places too. Because of that I think that in practice, in prod, add-on naming isn't actually a problem.

**Comment by rehandalal** [comment]
We got bit by this again today with a double upload of an extension.
