### ISSUE TITLE
Stop using public key sent from Autograph

### ISSUE THREAD

**Issue by mythmon** [mozilla/normandy#1890]
Currently, Normandy stores and validates the `public_key` field returned by autograph when signing objects. This is not used by Normandy Client when verifying recipe signatures. Instead the x5u is used to retrieve a certificate chain, which is a more sound verification process.

The server on the other hand *is* attempting to validate these signatures, which isn't good. To quote @jvehent on slack:

> ok so the public key field returned by autograph here isn't good
> the way to verify the signature is to use the chain from the x5u
> we'll need to remove it from autograph
> it should stop using the public key returned by autograph, and autograph should stop returning that value

We should remove the public key field from our database, and ignore it if Autograph sends it. We should stop validating it, and stop sending it to Normandy Client. None of this is a security problem, it is just not an optimal way of handling certificates and signatures.

**Comment by shell1** [comment]
we query it - so if they remove from their API we break.

**Comment by glasserc** [comment]
I'm not sure what to do with this issue. We currently now verify signatures using `x5u`. However, this signature verification is kind of slapdash -- we don't actually verify the cert chain. There are other places around Mozilla where we do this kind of verification -- see mozilla-services/poucave#106 -- and hopefully we should be able to standardize on a single solution. @g-k's comment on that issue links to three libraries claiming to implement this algorithm, but two are clearly marked as "work in progress" and the third doesn't inspire confidence either (`new` bugs older than a year).

Besides this, there's one other outstanding concern with Autograph in dev, which is that certs are served as `file://` URLs, which we don't support. See https://github.com/mozilla-services/autograph/issues/350. In the meantime, I've been developing against `autograph` 2.7.0 using `docker run -p 8765:8000 -it mozilla/autograph:2.7.0`.

The stated purpose of this issue is to stop using the public-key field of the Autograph response, but it seems to me that for old recipes, that may be the only way we have available to validate them (since `public_key` predates `x5u`). Absent any compelling certificate-chain-validation library to use, I don't think there's anything more that can be done on the Normandy side of this issue, so I'm closing it.
