### ISSUE TITLE
Normandy console errors are no longer displayed

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla/normandy#1916]
[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Affected Versions]:
- Firefox Nightly 69.0a1, Build ID 20190703162038

[Prerequisites]:
- Have access to the delivery console.
- Have 2 active opt-out recipes using the same add-on extension.
- Have a profile that can be targeted by the opt-out recipes.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Open the browser console and observe the console output.

[Expected result]:
- The "Cannot install study add-on for <experiment name>: an add-on with this ID is already installed." error is displayed.

[Actual result]:
- No errors are displayed in the console.

[Regression Window]:
- I could not reproduce this issue using the Firefox Nightly build from 2019-06-15, considering this I ran a regression check and narrowed it down to 2 builds. Here is the pushlog:
Last good revision: 51d26396dfafa7b5f45acc6c8c5f1dcf93bec486
First bad revision: 480fa12d68154837011c9a597f4848722ab9b805
Pushlog: https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=51d26396dfafa7b5f45acc6c8c5f1dcf93bec486&tochange=480fa12d68154837011c9a597f4848722ab9b805

[Notes]:
- None of the Normandy errors are displayed in the console.
- I have attached a screenshot with the console output from Beta (unaffected) and Nightly (affected):
![Normandy_consoles](https://user-images.githubusercontent.com/40393891/60644752-b4811f00-9e3f-11e9-99e0-fa882514ed63.png)

**Comment by mythmon** [comment]
Since this works with some client versions and not with others, this is not a server issue. This repository is only for server issues. Can you re-file this in Bugzilla under Firefox::Normandy Client?

Looking at the push log, I would bet this was caused by [bug 1544864](https://bugzilla.mozilla.org/show_bug.cgi?id=1544864). Could you also try and toggle the checkbox that as introduced with that bug, to see if the Normandy messages come back? If that's the case, that's still definitely a bug, but at least we'll have a place to look.

**Comment by Softvision-PatriciuPop** [comment]
I have retested this issue and after checking the "Show Content Messages" option the error messages are redisplayed. Sorry for the confusion, I will mark this issue as invalid.
