### ISSUE TITLE
Filter Object: Windows Build Number

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/normandy#2102]
We need to be able to filter for specific OS version and I believe this is only applicable for Windows.  It's not clear to me whether this will allow for some concept of a version range? @mythmon ?

**Comment by mythmon** [comment]
There are two kinds of OS versions that we can filter on.

The first is the Windows Version, which has values like 10.0, 6.2, and 6.1. These are the NT versions listed in the "Release version" column of [this table on Wikipedia](https://en.wikipedia.org/wiki/List_of_Microsoft_Windows_versions#Personal_computer_versions). Note that these are historically a little weird, for example the product released as "Windows 8.1" has an NT version of 6.3. For these we should probably have a list of versions, like we do for locales and countries. This is `normandy.os.windowsVersion` in JEXL. In UIs we should probably present this as just a list of checkboxes for Windows 7, 8, 8.1, and 10.

Since that version number doesn't change often, we also have access to another, finer grained identifier for windows, called the build number. The newest build number right now is 18363. For these we probably want a range of values, like we did for the date, profile creation date, and new version filters.

Technically we have similar options for OSX, but we haven't used them, so I don't think we should make filter objects for them right now. Lets just do Windows for now.

**Comment by uhlissuh** [comment]
@mythmon so are we thinking this should be two separate filters or do we want to try to roll it into one?

**Comment by uhlissuh** [comment]
I guess if it's one, we can have something passed in that specifies whether it's going to be filtering on`windowsVersion` or `windowsBuildNumber`.

**Comment by mythmon** [comment]
Given the different strategies in filtering these two types of versions that I proposed (a list vs a range), I think it would be simplest to make this in two filters. Having a filter that changes the type of inputs sounds tough.

**Comment by uhlissuh** [comment]
I'm going to make this ticket the ticket for the build number, and open a new ticket for windows version.
