### ISSUE TITLE
Upgrade migration recipe not sending telemetry pings

### ISSUE THREAD

**Issue by jtg567** [mozilla/normandy#292]
In contrast to other recipes, https://normandy-admin.prod.mozaws.net/control/recipe/25/ (last enabled ~6 days ago) has not pinged telemetry with any data - no data are found where the surveyId in the payload == 'out-of-date-3'

[see Spark gist](https://gist.github.com/jtg567/36f1fdb0e1db13113a435c8b32aeda6c), compare cells 6 and 7

**Comment by mythmon** [comment]
The spark gist looks fine to me.

Does it matter that we are only filtering 43.0.1, and not any other variant of 43, which I know exist. That shouldn't result in *zero* pings though.

Can we filter by Firefox 43 in Spark, to make sure that we have any data from the expected users?

One thing to keep in mind is that we expect to not have any data from Firefox 43 for some period of time, including some days when this recipe was active, due to #277.

**Comment by jtg567** [comment]
adding a `version= '43.0'` argument to cell 4 results in a count of zero records

to be clear, that's prior to any filtering by studyId

**Comment by jtg567** [comment]
Check the gist again; no heartbeat pings from any version before 46 going back as far as April 17.

**Comment by jtg567** [comment]
As discussed on #normandy, the recipe in question was active after Sept 30 and was probably affected by something other than [#277](https://github.com/mozilla/normandy/issues/277)

**Comment by mythmon** [comment]
I dug through the history of UITour. Telemetry reporting was added to Heartbeat in Firefox 46. Any version before that won't have any data in Telemetry. That explains why we can't find any 43 heartbeats in telemetry.
