### ISSUE TITLE
Add cache-control header to /{locale}/repair

### ISSUE THREAD

**Issue by relud** [mozilla/normandy#306]
required to serve entire site through akamai cdn

**Comment by mythmon** [comment]
I think that the first page clients hit, `/{locale}/repair`, is already cached (despite what I've said in the past). We set a TTL of 30 seconds for this right now, and we can easily configure this.

Do we actually want the index of the site to have cache headers? We don't expect any significant traffic to it, since it is just a bare page that says "Normandy", and we never send users there.

```
$ http -ph https://self-repair.mozilla.org/en-US/repair

HTTP/1.1 200 OK
Cache-Control: public, max-age=30
Connection: keep-alive
Content-Encoding: gzip
Content-Length: 292
Content-Type: text/html; charset=utf-8
Date: Wed, 26 Oct 2016 23:22:37 GMT
X-Cached: HIT
X-Frame-Options: DENY
strict-transport-security: max-age=15768000; includeSubDomains
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
```
