### ISSUE TITLE
Switch to an authentication provider

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#367]
In general we don't prefer to run our own separate authentication, but instead prefer to rely on an auth provider. This would help with things like having to encrypt and send passwords to new users, having to implement a password-change UI for the control interface, etc.

@jvehent I hear Auth0 is ready for primetime. Is using that as the in-site auth, paired with VPN access, sufficient for Normandy?

**Comment by jvehent** [comment]
The current standard for admin panel authentication is LDAP. `auth0` is being prototyped by infosec but we're not yet ready to integrate it on our admin panels. I'm staying on top of it, I'll let you know when it's good to go.

And, indeed, you should store passwords. Use LDAP ;)

**Comment by Osmose** [comment]
@jvehent How about Okta via OpenID, so that we can switch to Auth0 when it's ready?

**Comment by jvehent** [comment]
Okta isn't always the easiest to integrate with, because applications need to be created in the okta admin. We've used OIDC with Google, which itself talks to Okta, but only for public sites and not for admin panels.

There are a few questions that need to be addresses, like how would we manage groups membership? I do want to get rid of direct LDAP as early as possible, but for the time being this is what Normandy should use. (Note: nginx can take care of it for you).

**Comment by mythmon** [comment]
We integrated with Auth0 a while ago.

**Comment by mythmon** [comment]
We integrated with Auth0 a while ago.
