### ISSUE TITLE
Add storage durability checks to add-on

### ISSUE THREAD

**Issue by mythmon** [mozilla/normandy#433]
Self-repair checks that storage is durable before testing it. The add-on driver should do the same thing.

**Comment by Osmose** [comment]
This got backed out in https://github.com/mozilla/normandy/commit/fda562a17849f1d231d94ea707f59e3c43e3e33f.

**Comment by Osmose** [comment]
Also, after working through how durability checks affect the `show-heartbeat` action, I think we should not throw errors when storage isn't durable, because it makes it difficult to track when a recipe might fail due to durability issues. Specifically for `show-heartbeat`, I had trouble figuring out if it displayed the heartbeat prompt before doing anything with storage.

Instead, I think there should be a "isDurable" method on storage instances that allows recipes to choose when to check for storage durability, to allow them to fail gracefully.

Thoughts?

**Comment by mythmon** [comment]
I originally advocated for throwing errors, as a way of not trusting actions to do the right thing, and centralizing the checking of durability. Now that I've seen it in action a bit, I think that wasn't the right decision.

I think adding `isDurable` as a storage method and removing the non-durable throw makes sense. 👍

**Comment by mythmon** [comment]
We've been running without this check for a while now without any major issues, and the failure cases that applied to self-repair don't apply here.
