### ISSUE TITLE
Distribution Based Recipe not Showing

### ISSUE THREAD

**Issue by rayborn** [mozilla/normandy#464]
@mythmon 

Distribution ID based recipe(s) not showing

- Tried "showHeartbeat" and "Log to Console"
- Tried fresh profile
- Tried overriding with about:config's distribution.id

Recipes:

- ShowHeartbeat: https://normandy-admin.prod.mozaws.net/control/recipe/117/
- Console: https://normandy-admin.prod.mozaws.net/control/recipe/118/

Ping rrayborn for Funnelcake used.  It's windows only.

This is an important component of a Growth experience going out next week.

**Comment by rayborn** [comment]
>This is an important component of a Growth experience going out next week.

This also means that fixes can be merged rapidly if I/we talk with the release engineers driving this change.

Funnelcake Bug: https://bugzilla.mozilla.org/show_bug.cgi

**Comment by mythmon** [comment]
@rayborn The link to the Funnelcake build is broken. I have a Windows VM I can test this on now, if you can get me the Funnelcake build.

**Comment by rayborn** [comment]
Sorry, fixed.  Quick copy/paste of dynamic page :/

**Comment by mythmon** [comment]
Using Funnelcake 100 from the bug and fresh profile, recipe 118 (console-log) is working fine for me.

**Comment by mythmon** [comment]
My previous tests was installed with the stub installer. I have now also tested using the non-stub installer, and it also worked.

Another interesting thing heartbeats won't show the first time a profile is started, since we don't show heartbeats if we aren't confident that our storage is durable (this prevents spamming people with security add-ons). Only on the second start up will we have enough information be confident in showing heartbeats.

**Comment by rayborn** [comment]
Great, thanks for taking the time to validate this mythmon.  I think that we're good to go.
