### ISSUE TITLE
CSP prevents inline style editing 

### ISSUE THREAD

**Issue by andymikulski** [mozilla/normandy#621]
Attempting to edit 'inline' styles via the Firefox devtools results in a CSP error and the styles not applying to the DOM element.

Steps to reproduce:

- Open devtools, use element inspector to select any element
- Add styles to the [element's inline section](https://cloud.githubusercontent.com/assets/2767162/24156784/29b6f6e2-0e1d-11e7-8fc9-1d2ffb5f6deb.png).
- Notice a `Content Security Policy` in console as you enter styles:

```
Content Security Policy: The page’s settings blocked the loading of a resource at self (“default-src https://localhost:8000”). Source: color: #000;.
```

Here, `color: #000;` was the attempted styling - you'll notice the CSP error throws as you type out the style. No styles are applied to the page.

Interestingly, editing styles within existing selectors/classes is fine - no CSP errors, applies to the page correctly. I think the devtools are attempting to append a `<style>` tag to the page and the CSP settings aren't cool with that - but that's a total guess.

**Comment by mythmon** [comment]
For completeness, here is the CSP report that is sent to the report URL:

```json
{
  "blocked-uri": "self",
  "document-uri": "https://localhost:8000/control/",
  "original-policy": "block-all-mixed-content; form-action https://localhost:8000; object-src 'none'; frame-src 'none'; default-src https://localhost:8000; base-uri 'none'; report-uri https://localhost:8000/__cspreport__",
  "referrer": "",
  "script-sample": "background: #000;",
  "source-file": "https://localhost:8000/control/",
  "violated-directive": "default-src https://localhost:8000"
}
```

This is also the most common violated directive we see in prod, based on the CSP report logs. I think this requires a bit more research to figure out what the right thing to do is. I'm open to suggestions. Is it safe to enable `default-src self`? Or would that open us up to attacks?

CC @jvehent

**Comment by mythmon** [comment]
@g-k Do you know anything about CSP and the Firefox devtools?

**Comment by andymikulski** [comment]
Additional info: clicking the [Add new rule](https://cloud.githubusercontent.com/assets/2767162/24172308/5a77c0ce-0e4d-11e7-8a52-abe5dc000d5b.png) button doesn't do anything, but it should add a new style for the selected element's class/selector

**Comment by g-k** [comment]
Interesting. 

@mythmon What user agent(s) are you getting that CSP report for? default-src 'self' and `localhost:8000` should be fine to swap. They're equivalent except for the protocol, but that should be enforced elsewhere with HSTS and HPKP headers. I'd add `frame-ancestors` `'none'` too if the page isn't framed anywhere.

For devtools when `'unsafe-inline'` isn't in `style-src`, I'd guess CSP blocks adding a style if it's implemented as inserting an inline style tag or adding a style html attribute to the element and doesn't block modifying an existing CSS rule for that element. I'd expect devtools to bypass CSP in this case, so you might check if that's intended behavior in #contentsecurity on IRC (I can do that too if you want since I'm curious).

**Comment by mythmon** [comment]
The CSP report in my last comment was produced by following the steps to reproduce that @andymikulski provided. Specifically I was using Nightly.

As discussed in #604, we can't use `frame-ancestors 'none'` right now, because we require framing of some pages by [parts of Firefox](https://dxr.mozilla.org/mozilla-central/source/browser/modules/SelfSupportBackend.jsm#256-273) which [as far as we can tell don't have a origin that can be named](https://github.com/mozilla/normandy/pull/604#issuecomment-286104143).  We also can't remove `frame-ancestors` only on the page needed, because of mozilla/django-csp#85.

We use the header `X-Frame-Options` to deny framing, and this works because the parts of Firefox we require being framed in ignores `X-Frame-Options`.

I'll ask in #contentsecurity about the devtools and CSS.

**Comment by wolfgang42** [comment]
Since this CSP+devtools issue showed up in a search when I had this problem on my own site, here's the Firefox bug report: [Bug 1391994 - CSP blocks editing style](https://bugzilla.mozilla.org/show_bug.cgi?id=1391994)

**Comment by mythmon** [comment]
This isn't a Normandy issue. For future progress, watch the Firefox bug.
