### ISSUE TITLE
Nothing Burger Experiment

### ISSUE THREAD

**Issue by mythmon** [mozilla/normandy#734]
The Nothing Burger Experiment is the first preference experiment we are going to run. It is going to change an inconsequential preference, and make sure that the data collection pipeline is working. Preference experiments have landed in mozilla-central, and should be available on Firefox 55 Nightly soon.

The things we need to do for the experiment are:

* [x] Verify that version 51 of shield-recipe-client is available in Nightly
  * Expected to be in  Nightly 2017-05-04
* [x] Pick a preference to run the experiment on: test.normandy.prefflip.defaultpref
* [x] Pick the branches and values for the preference
  - control:  0, weight: 3
  - versionA: 1, weight, 2
  - versionB: 2, weight, 1
* [x] Write a filter expression that targets nightly and a small sample rate
* [ ] Set up analysis on telemetry to catch the experiment data
* [x] Make a recipe targeting incorporating the above
* [ ] Wait
* [ ] Gather data

**Comment by gregglind** [comment]
name: test.normandy.optout.defaultpref

Branches:  values
- control:  0, weight: 3
- versionA: 1, weight, 2
- versionB: 2, weight, 1

**Comment by gregglind** [comment]
I well email rel-man en momento.

**Comment by gregglind** [comment]
relates to:  https://bugzilla.mozilla.org/show_bug.cgi?id=1350907

**Comment by gregglind** [comment]
Updates:

Rob Hudson did a gist of some packets at  https://gist.github.com/robhudson/0678665c205ce02c0976c0956fa4d809

1.  Sampling rate *probably* works.  He gets 0.5% of nightly.  We expected 1%.  This could have something to do with vagaries of Nightly sessions being short, or bots or who knows.
2.  Tagging with branch works.
3.  Proportional assignment works.
4.  Unclear if constant (deterministic) assignment works, because I forgot to ask.
5.  Unknown if value setting works.

Re point 5:  So, we chose a pref that isn't instrumented in telemetry.  I suggest we re-try this with a different pref, as will be seen by UT.  

Code:  https://dxr.mozilla.org/mozilla-central/source/toolkit/components/telemetry/TelemetryEnvironment.jsm#158

**Comment by gregglind** [comment]
(looking further, it looks like UT only watches a finite list of prefs :(  So we might have to approach this a different way. )

**Comment by robhudson** [comment]
[Gist](https://gist.github.com/robhudson/0678665c205ce02c0976c0956fa4d809) updated to show a 0.77% sampling on nightly and constant (deterministic) assignment is working.

**Comment by gregglind** [comment]
I claim this is closed, and we learned all that we can learn from it.  Let's turn it off, and make sure it stays dead.
