### ISSUE TITLE
Mystery Meat 301s

### ISSUE THREAD

**Issue by mythmon** [mozilla/normandy#753]
Since the system add-on has shipped, we are receiving a lot of expected 301s, due to #719. (#719 is fixed in master, but not shipped yet)

We are also getting some unexpected and unexplained 301s. There are a couple weird things here:

* We occasionally get about 3x the amount of 301s for an hour.
* We are gettings 301s on self-repair.mozilla.org, which isn't supposed to get add-on traffic.
* We get small bumps in 301s on the hour every hour.

Current theories are that there are organizations that start up a bunch of Firefox instances for automation on a cron job, or that there is something in Firefox's update timer that causes it to cluster around certain times.

## Graph of 301s on `self-repair.mozilla.org` (blue) and `normandy.cdn.mozilla.net` (purple) over a 24 hour period

![shot_23363](https://cloud.githubusercontent.com/assets/305049/25876494/6d298ec2-34d2-11e7-8e26-9a971235daf5.png)

This issue covers figuring out what is going on here, and if it is reasonable, fixing it.

CC @relud

**Comment by Osmose** [comment]
Looks like this has mellowed out? Here's the past week of 3xx responses:

<img width="737" alt="screen shot 2017-06-16 at 1 48 17 pm" src="https://user-images.githubusercontent.com/193106/27244248-8b30bfcc-529a-11e7-977a-0ee4f64ef50a.png">

Shall we call this ambiently resolved?

**Comment by mythmon** [comment]
@relud This is that Nginx caching oddness you investigated, I think. Can you link to or provide some info about that here?

**Comment by relud** [comment]
The nginx oddness is gone, the root cause was fixed.

It was caused by: 

normandy returned a 301 to https (which got cached for 1 hour, then served from stale cache) for a request that was already on https, on a path that was not supposed to be cached. This happened on about 10 of 30 running servers.

if nginx has no cache for a url, it passes it through. if nginx has a valid cache, it serves the cached response. if nginx has a stale cache for a url, it will pass the first request through, and return the cached response to all following requests until the passed request completes. When the passed request completes, if the response would get cached the cache is updated. If the response would not get cached, then nginx will continue the pattern for serving a stale cache indefinitely. the 301s in question were served from stale cache indefinitely, causing this issue.
