### ISSUE TITLE
Insert telemetry values into Heartbeat post answer URL

### ISSUE THREAD

**Issue by MattGrimes** [mozilla/normandy#769]
In certain situations we are going to be looking for changes in attitudinal feedback based on different values available in Telemetry. It would be nice if we could pass the values of interesting prefs in as URL params to Survey Gizmo. That would allow us to do custom survey logic to alter the order/phrasing/reponse types of individual questions based on these values. This is not possible with the current system of merging on telemetry AFTER the survey is complete. This method will significantly decrease the amount of analysis time for these surveys as well. 

Use cases:

- I ran a pref flipping experiment to change the value of nglayout.intial.paintdelay. The default value is 350ms but setting it to 0 should make users feel like Firefox is faster. I put out a Heartbeat survey and in the jexl I limit it to only users with that experiment id. 

- I want to know if having the dev toolbar open is a good predictor of being a developer. I want to split my survey based on the value of dev.toolbar.open

- I want to know if people that restore the previous session are happier than people that always get the home page on startup. So I want to compare the values of browser.startup.page

cc @gregglind @rayborn anything else you want to add?

**Comment by Osmose** [comment]
I have some concerns about this:

1. Do you want to just specify a list of preferences that get sent? We will have to ship client updates every time this list changes.

2. We might want to consider whitelist the domains that are sent this data. Otherwise, any domain we link to from a Heartbeat prompt will get this data in the query string.

3. I'd like us to get approval from a privacy steward (data steward? I can never remember the title) for sharing this data before we consider implementing this, specifically because heartbeat prompts can send users to arbitrary domains rather than only Mozilla-controlled domains, depending on the recipe configuration.

**Comment by MattGrimes** [comment]
1. I think we'd want to be able to choose 1 or more per recipes. Sending EVERYTHING that might be interesting EVERY TIME seems like overkill.

2. Good point. If we are specifying on a per survey basis it's not a big issue, but probably nice to have for security reasons anyway.

3. Adding @rjweiss to comment. I think if we have a whitelist as discussed in 2 AND this is only available as needed per 1 we should be fine.

**Comment by rjweiss** [comment]
Yes, I think you will need to come up with this whitelist, or generically only work with "trusted" Mozilla pages (e.g. about:addons, etc.)  To be honest, this is beyond a simple data stewardship review, and you need to talk to Policy/Legal about this proposal.

**Comment by mythmon** [comment]
I think that this is too risky to do in a generic way. I suggest that surveys that need this functionality should be done through add-on studies, and go through their own policy and data reviews.
