### ISSUE TITLE
Need to be able to target recipe on profile creation date

### ISSUE THREAD

**Issue by rayborn** [mozilla/normandy#777]
@raymak is helping marketing with their "lifecycle management" study.  We're interested in targeting new users as defined by their profile creation date in Telemetry ("creationDate").  This is in a  date string format: "2017-05-23T21:14:23.539Z".

We need some method of targeting users that are within N days of creationDate in their life cycle.  We are agnostic to the solution.  The following would probably be rational, and reusable for other targets: but I think casting a string date to a timestamp int:

* Add a function for getting the current datetime in string or int (time since epoch)
* Add a function to cast a string datetime to an int (time since epoch)

e.g. ( (today() - toTimestamp(creationDate) ) / (24 * 60 * 60) ) > 14

Obviously we need to be conscious of all of the fun baggage that comes with dates :)

**Comment by Osmose** [comment]
You actually can do this today, because:

- Server time is available as [`normandy.request_time`](http://normandy.readthedocs.io/en/latest/user/filter_expressions.html#normandy.request_time) in filter expressions.
- You can convert a string to a date using the [`date`](http://normandy.readthedocs.io/en/latest/user/filter_expressions.html#date) transform.
- Subtracting one date from another in JS returns an integer with the number of milliseconds different between the two dates.

So something like this would work:

```js
# Match users who's creationDate is less than 24 hours
((normandy.telemetry.creationDate|date - normandy.request_time) / (1000 * 60 * 60)) < 24
```

The main problem with this: `creationDate` in the main telemetry packet is not the date the profile was created, it's the date the ping itself was created. I believe you're looking for `environment.profile.creationDate`, which is not a date string, but instead is [the number of dates since the profile was created](http://gecko.readthedocs.io/en/latest/toolkit/components/telemetry/telemetry/data/environment.html).

So unless you need precision better than days, the data you want isn't even in telemetry. Or am I mistaken?

**Comment by raymak** [comment]
The latter should work well enough for what the marketing and engagement teams want. But I have a question about the first method. Normandy client looks at the most recent main ping, right? So does that mean that normandy.telemetry.creationDate is alwasys a fairly recent date? And if yes, can we actually use that to infer the amount of time the user has been inactive for? I.e. the approximate time between the last time the user has used Firefox and their current session.

**Comment by Osmose** [comment]
> Normandy client looks at the most recent main ping, right? 

Yes.

> So does that mean that normandy.telemetry.creationDate is alwasys a fairly recent date? 

I can't say for sure, but I would guess no. I believe that date is set by the client, and client clocks are very untrustworth for absolute times (which is why the duration-based measure is probably the better one).

> And if yes, can we actually use that to infer the amount of time the user has been inactive for? I.e. the approximate time between the last time the user has used Firefox and their current session.

I don't think so, because when the client sends data to our servers probably isn't correlated with when their session started. They could be sending the ping at any time relative to when it was created.

If you want to know for sure, though, you should ask the Telemetry team.

Given that the existing measure is suitable for this campaign, I'm going to call this issue closed. We can reopen or re-file if, in the future, we want greater-than-per-day precision.
