### ISSUE TITLE
Content Security Policy error when saving recipes

### ISSUE THREAD

**Issue by raymak** [mozilla/normandy#796]
I sometimes get this in my console when saving a recipe. The recipe is then not saved and I get the notification bar message to correct my errors.

Content Security Policy: The page’s settings blocked the loading of a resource at https://auth.mozilla.auth0.com/authorize?scope=openid%20email%20profile&client_id=[...]&state=19ee113c68300fad49e234f3f8e6b8e2&nonce=12ab40212f95f801c3841df355cb41e7&redirect_uri=https%3A%2F%2Fnormandy-admin.prod.mozaws.net%2Fauth%2Flogin&response_type=code (“default-src https://normandy-admin.prod.mozaws.net”).

**Comment by mythmon** [comment]
@raymak Could this be after having the tab that Normandy is in open for a while? I'm guessing that the auth0 session is expiring, and when making an API request the page is getting a redirected to auth0.

If you didn't get a CSP error you'd get a different kind of error since our client can't handle this right now, but at least we could provide a nicer error message.

**Comment by raymak** [comment]
@mythmon Yes, it must be it because I could fix it by opening a new Normandy control page and logging in again.

**Comment by mythmon** [comment]
I think this is mostly a duplicate of #345 then.
