### ISSUE TITLE
Implement uptake telemetry

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#802]
@leplatrem [announced uptake telemetry](https://mail.mozilla.org/pipermail/firefox-dev/2017-June/005475.html) on a bunch of Firefox lists today. It helps measure uptake of update systems via Telemetry histograms. It looks rad.

This is totally a thing we want to know about Shield. We should use this.

@leplatrem With Shield, we deliver and execute several recipes when out client hits our service. Some may fail while others may succeed. Is uptake telemetry suitable for measuring the uptake of each individual recipe? Could we add a unique per-recipe identifier to the source name when calling the API? Or is it more suitable for measuring uptake of the service as a whole?

Also, for Telemetry I'm mostly familiar with ATMO and ReDash. How are we expected to view the data being sent?

CC @rhelmer since he might be more familiar with Shield and was involved in uptake telemetry.

**Comment by leplatrem** [comment]
Thanks for the kind words and your immediate interest :)

> Is uptake telemetry suitable for measuring the uptake of each individual recipe? Could we add a unique per-recipe identifier to the source name when calling the API? 

Yes, definitely, you choose the way you build the key for each source (e.g. `shield-recipe-{id}` would be valid).

I haven't looked it into it yet, but I'm pretty confident that we could aggregate all the keys that start with a string (e.g. `LIKE 'shield-recipe-%').

> Also, for Telemetry I'm mostly familiar with ATMO and ReDash. How are we expected to view the data being sent?

Since the underlying tools are just plain telemetry — keyed and categorical — histograms, you shouldn't have any issue with this. 
If I remember well, according to Rob, the challenge is to find a good sampling strategy. 

We should definitely add some guidelines (or query templates) somewhere to ease the retrieval of data.

If you need some help, or want to share some feedback, please don't hesitate to ping me :)

**Comment by rhelmer** [comment]
More specifics on sampling and getting useful data out of redash:

The `longitudinal` dataset rolls a lot of things up for you (each row contains a unique client ID and all the rest of the data is present as arrays on each row) and makes this easier although due to the size of the data you still must take a sample. The larger problem is that it is only updated once per week.

To get data closer to real time, there is a `main summary` dataset that is updated more often (close to real-time IIRC), but as the data hasn't been rolled up as above it's a huge number of rows so you must take a very tiny sample to keep from melting the infra.

I have less experience with ATMO but my understanding is that you must write a map/reduce job or a Jupyter notebook and have that job run regularly.

There's also a tool called Hindsight that allows writing plugins for custom real-time analysis - I have used the output of these to track custom pings but haven't set them up myself.

More info at https://wiki.mozilla.org/Telemetry and folks in #telemetry on irc.m.o have been very helpful for me in the past.
