### ISSUE TITLE
Annotate studies with new experiment type option

### ISSUE THREAD

**Issue by georgf** [mozilla/normandy#856]
In [bug 1376599](https://bugzilla.mozilla.org/show_bug.cgi?id=1376599) we added an option to `TelemetryEnvironment.setExperimentActive()`.
The updated docs will be available [here](https://gecko.readthedocs.io/en/latest/toolkit/components/telemetry/telemetry/collection/experiments.html) soon.

We will have this new option on Firefox 56 or 55.

We expect to have at least the pref-flip experiments tagged with an actionable type.
E.g. they could use the recipe action types ("show-heartbeat", "preference-experiment").
It would be good to coordinate with Sunah for the specific annotation types.

**Comment by sunahsuh** [comment]
I think the only thing I would add here is that prefixing the actions with `normandy-` would probably help with namespacing.

It's pretty important for us to get this done soon since there's a decent chance pref rollouts will overwhelm the data pipeline if we don't exclude them. @Osmose can you help us get this on the docket?

**Comment by Osmose** [comment]
@rehandalal Do you have bandwidth to take this on?

**Comment by sunahsuh** [comment]
Hey @rehandalal do you have an update on this bug?

**Comment by Osmose** [comment]
Taking this from @rehandalal to see if I can sneak it in with the next opt-out sync.
