### ISSUE TITLE
Create unique ids for certain DOM elements to make automated UI testing more sustainable

### ISSUE THREAD

**Issue by 18epedersen** [mozilla/normandy#927]
I've added TODO comments in my locators.py file, which indicate which DOM elements I would like to have unique ids to make automated testing easier and more sustainable. 

https://github.com/18epedersen/Normandy-e2e-tests/blob/dev/pages/locators.py

**Comment by andymikulski** [comment]
@18epedersen I think it'd be beneficial if you made a complete pass over the site and determined what needs ID's/etc, so we can get them all put in place in one go (versus frequent requests/updates).

You can use github's `- [ ]` formatting to make a checkbox to better track progress as well, e.g.:

- [x] Add ID to this thing
- [ ] Add ID to that thing

**Comment by 18epedersen** [comment]
- [ ] Add unique ID to home breadcrumb

- [ ] Add unique ID for the extensions button on the home page

- [ ] Add a unique ID for the console-log option (in the action dropdown)

- [ ] Add a unique ID for the show-heartbeat option (in the action dropdown)

- [ ] Add a unique ID for the preference-experiment option (in the action dropdown)

- [ ] Add a unique ID for the add branch button in the new recipe page

- [ ] Add a unique ID for both the true/false options in the add branch dialog in the new recipe page

- [ ] Add a unique ID for the opt-out-study (in the action dropdown) in the new recipe page

- [ ] Add a unique ID to the publish button on the view recipe page

- [ ] Add a unique ID to the ok button on the view recipe page

- [ ] Add a unique ID to the approve button on the approval history page

- [ ] Add a unique ID to the selected action on the clone recipe page

- [ ] Add a unique ID for the upload xpi button on the new extensions page

- [ ] Add a unique ID for the save button on the new extensions page

**Comment by 18epedersen** [comment]
- [ ] Add a unique ID for the view recipe breadcrumb

- [ ] Add a unique ID for the action name field on the view recipe page

**Comment by andymikulski** [comment]
Opened PR #970 for these additional requests. Some notes for @18epedersen:

Add a unique ID for the console-log option (in the action dropdown)
Add a unique ID for the show-heartbeat option (in the action dropdown)
Add a unique ID for the preference-experiment option (in the action dropdown)
Add a unique ID for the opt-out-study (in the action dropdown) in the new recipe page
Add a unique ID to the selected action on the clone recipe page
 - We can't use an ID for this due to the front end library we're using.
 - We _can_ use **classes** instead - e.g. instead of `#rf-console-log`, we can use `.rf-console-log`

Add a unique ID to the ok button on the view recipe page
 - This doesn't appear to exist

**Comment by 18epedersen** [comment]
@andymikulski If you can use classes for the ones listed above that would be great!

**Comment by 18epedersen** [comment]
<img width="1199" alt="screen shot 2017-08-09 at 9 28 55 am" src="https://user-images.githubusercontent.com/10553640/29132464-292e12c8-7ce5-11e7-9570-b99087cda82a.png">

For the ok button, I'm referring to this pop-up when you want to publish a recipe.

**Comment by andymikulski** [comment]
@18epedersen It turns out that we can't add a class to either the button OR the modal, due to the version of Ant we're using.

You should be able to target the button using the selector `.ant-modal .ant-btn-primary` instead.
