### ISSUE TITLE
Collect and expose aggregate uptake counts via the API

### ISSUE THREAD

**Issue by Osmose** [mozilla/normandy#951]
In #802 we added [data collection for recipe executions and failures](http://normandy.readthedocs.io/en/latest/user/data_collection.html). Now we need to make this data available via the Normandy API.

Some sample use cases of this API:
- Displaying overall success/failure counts on the detail page for a recipe.
- Graphing execution rates over time for a single recipe.
- Alerting when failure rates rise above a threshold for a given period of time.

Todo:
- [ ] Design API for getting uptake information
- [ ] Design method for pulling uptake data from telemetry into Normandy
- [ ] Determine whether this API can be public, or needs to be limited to the admin node only, which is behind the VPN.

**Comment by hannosch** [comment]
I've put together a first prototype for extracting the data from Telemetry. I think all the data we want is available from the public Telemetry aggregates. Prototype code is over at https://github.com/hannosch/normandy-telemetry. The data we can extract this way is at https://github.com/hannosch/normandy-telemetry/blob/master/exporter/data/histograms/UPTAKE_REMOTE_CONTENT_RESULT_1.json

The code is based on the Cerberus exporter code (part of telemetry alerts / https://docs.telemetry.mozilla.org/tools/alerts.html). My hope is that we could put the email alerting code into cerberus / medusa, so it lives in a central place for detecting and reporting on changes in Telemetry data. Cerberus has some nice features for detecting changes in the shape of histograms we might be able to re-use. Medusa is the web frontend and lives over at http://alerts.telemetry.mozilla.org/index.html#/detectors/1/alerts/?from=2017-07-15&to=2017-08-15&metrics-filter=

Since it's possible to extract per-recipe data from the public telemetry API, we can probably get this data directly from telemetry on each recipe web page, without having to store it inside Normandy, but simply fetch it as needed.

Another possible approach is to use the exporter code and load all the data into Normandy. Than design new HTTP APIs to power per-recipe dashboards and act on the local data to provide the email alerting features.

**Comment by mythmon** [comment]
> Since it's possible to extract per-recipe data from the public telemetry API, we can probably get this data directly from telemetry on each recipe web page, without having to store it inside Normandy, but simply fetch it as needed.

If it is reasonable to do so, I think this is the best way forward. It doesn't require changes to the server, which makes it easier to develop and iterate on. If querying these values on each recipe page isn't efficient enough, we can explore loading the code into Normandy's database.

**Comment by mythmon** [comment]
The APIs that hannosch pulled from do not work for release. I'm working with the telemetry team to get this data from another source.

**Comment by mythmon** [comment]
The APIs that hannosch pulled from do not work for release. I'm working with the telemetry team to get this data from another source.

**Comment by mythmon** [comment]
I claim that although Normandy Client is generating this data, it is not Normandy Server that needs to collect and expose this data. This sort of dashboarding and data analysis belongs in other projects, such as Experimenter and Test Tube.
