### ISSUE TITLE
Add server side shield identicons

### ISSUE THREAD

**Issue by mythmon** [mozilla/normandy#988]
This is specs for @marcrowo's benefit.

`/api/v2/recipe/` should have a new field, `identicon_seed`. It should validate that the seed is of the format `generation:seed`, like `v1:asdfasdf`, where the first part is always `v1` (for now), and the second part is any string. If no generation is supplied in the  API, it may add a `v1:` prefix.

There should be a new API, `/api/v2/identicon/${generation}:${seed}.svg` that returns a SVG shield identicon using stable-random generation techniques, like in #983. This should always return the exact same output for the same input, and there should be a test for this.

**Comment by marcrowo** [comment]
@mythmon @andymikulski Something I noticed was that in some cases the stripe colors can be the same as the background color. I'm not sure if this is intentional or if I made a mistake in my implementation?

Original shield (hex codes also match so I am fairly confident that the color is the same):
![screenshot-2017-8-21 http localhost](https://user-images.githubusercontent.com/1198628/29540182-129e6494-8682-11e7-8020-c5a45c39340e.png)

Same shield with black stripes:
![screenshot-2017-8-21 http localhost 1](https://user-images.githubusercontent.com/1198628/29540237-4b3d42d4-8682-11e7-8286-639b45f82349.png)

This does not occur for all striped shields, ex: 
![screenshot-2017-8-21 http localhost 2](https://user-images.githubusercontent.com/1198628/29540257-65e32112-8682-11e7-86b4-2a517f1467fc.png)

**Comment by andymikulski** [comment]
@marcrowo As I understood it, there was a chance of no stripes at all, which is what I assumed was happening here. IMO, what you've run into here is fine as-is, but if you want to force different colors, I'm totally on board. @mythmon can feel free to disagree though

**Comment by mythmon** [comment]
There is a chance of having a solid shield, with no stripes. @marcrowo was pointing out that sometimes he was observing generated stripes with the same colors as the background. When looking over the python version of the code, we found that the luminescence check was backwards. It wasn't rejecting similar colors, included identical colors. That caused same color background and stripes.

**Comment by marcrowo** [comment]
This should be fixed in 705e51c.
